import { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import Footer from "../Components/Footer";
import Header from "../Components/Header";
import { Spacing } from "../Components/Spacing";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en" className="bg-black text-white">
        <body className={(inter.className, "bg-black")}>
          <Header />
          <main className="min-h-screen">{children}</main>
          <Spacing size="sm" />
          <Footer />
        </body>
      </html>
    </SessionProvider>
  );
}
