import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import Footer from "../Components/Footer";
import Header from "../Components/Header";
import { Spacing } from "../Components/Spacing";
import { Toaster } from "react-hot-toast";
import { auth } from "@/auth";
import "./globals.css";
import "../styles/product.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={(inter.className, "bg-black")}>
          <Header />
          <main className="min-h-screen">{children}</main>
          <Spacing size="sm" />
          <Footer />
          <Toaster position="bottom-right" />
        </body>
      </html>
    </SessionProvider>
  );
}
